plugins {
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.kotlinAndroid)
}

android {
    namespace 'com.cerebus.tokens.reinforcement_photo'

    defaultConfig {
        minSdk 28

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation project(path: ':core:logger')
    implementation project(path: ':core:ui')
    implementation project(path: ':data:reinforcement')

    implementation libs.androidxCoreKtx
    implementation libs.androidxAppcompat
    implementation libs.material
    implementation libs.navigationFragmentKtx
    implementation libs.navigationUiKtx
    testImplementation libs.junit
    androidTestImplementation libs.androidxTestJunit
    androidTestImplementation libs.androidxTestEspresso
    implementation libs.viewbindingDelegate

    implementation libs.koinAndroid
    implementation libs.koinTest
}
