package presentation.tokens_screen.mvi_contracts.reinforcement_image_mvi_contract

import presentation.tokens_screen.mvi_contracts.Event

interface ReinforcementEvent : Event

class GetReinforcementStateEvent : ReinforcementEvent